name: Deploy
run-name: Deploying to prod 🚀
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
    