name: Deploy
run-name: Deploying to prod 🚀
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: ls
      - name: cd Into App Directory
        run: cd ./app
      - name: Deploy to Prod
        run: npm run deploy
